---
    - name: Enable nginx repository
      copy: src=roles/gogs/files/nginx.repo dest=/etc/yum.repos.d 
    - name: Install dependency for SELinux configuration
      package: name=libsemanage-python state=present
      when: ansible_selinux
    - name: Allow nginx to do network connects (SELinux)
      seboolean: name=httpd_can_network_connect state=yes persistent=yes
      when: ansible_selinux
    - name: Install required packages
      yum:
        name: "{{item}}"
        state: latest
      with_items:
      - "{{req_packages}}"
    - name: Create gogs user
      user: 
        name: "{{gogs_user}}"
        state: present
        home: /opt/gogs
        createhome: yes
    - name: Download gogs package
      get_url: 
        url: "{{gogs_package}}"
        dest: /opt/gogs.tar.gz
    - name: Create directory structure
      file:
        path: "{{item}}"
        state: directory
        owner: gogs
        group: gogs
      with_items:
      - "{{gogs_dirs}}"
    - name: Untar gogs 
      unarchive:
        remote_src: yes
        src: /opt/gogs.tar.gz
        dest: /opt
    - name: 
      file:
        path: "{{gogs_conf_dir}}"
        state: directory
        owner: gogs
        group: gogs
    - name: Copy gogs service file
      copy:
        src: files/gogs.service
        dest: /etc/systemd/system/gogs.service
    - name: Copy gogs configuration file
      copy: 
        src: files/app.ini
        dest: "{{gogs_conf_dir}}app.ini"
    - name: Set gogs dir & file permissions
      file:
        path: "{{item}}"
        owner: gogs
        group: gogs
        recurse: yes
      with_items:
      - "{{gogs_dirs}}"
      - "{{gogs_conf_dir}}"
    - name: Start and enable gogs
      systemd:
        name: gogs
        state: started
        enabled: yes
    - name: Start and enable nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
    - name: Remove /etc/nginx/conf.d/default.conf file
      file: 
        path: /etc/nginx/conf.d/default.conf 
        state: absent
    - name: Copy nginx configuration file
      copy: 
        src: roles/gogs/files/gogs.conf 
        dest: /etc/nginx/conf.d/gogs.conf
        owner: root 
        group: root 
        mode: 644 
        force: yes
      notify:
        - Reload nginx
